// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkP-ZSaQCz5JTRGjJSNJ33oFQDeY8meHw',
    appId: '1:885350117808:web:44196f523dfca17cbde675',
    messagingSenderId: '885350117808',
    projectId: 'appod-3f4d9',
    authDomain: 'appod-3f4d9.firebaseapp.com',
    storageBucket: 'appod-3f4d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4EixJE9nILmS0CD4KSXSZZQM5KA4Tib0',
    appId: '1:885350117808:android:695c4cf117f0ea18bde675',
    messagingSenderId: '885350117808',
    projectId: 'appod-3f4d9',
    storageBucket: 'appod-3f4d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq9Vz_S_BtwSaDrxab17fJQabuLqdFwoA',
    appId: '1:885350117808:ios:51bffd09d661da0cbde675',
    messagingSenderId: '885350117808',
    projectId: 'appod-3f4d9',
    storageBucket: 'appod-3f4d9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq9Vz_S_BtwSaDrxab17fJQabuLqdFwoA',
    appId: '1:885350117808:ios:51bffd09d661da0cbde675',
    messagingSenderId: '885350117808',
    projectId: 'appod-3f4d9',
    storageBucket: 'appod-3f4d9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkP-ZSaQCz5JTRGjJSNJ33oFQDeY8meHw',
    appId: '1:885350117808:web:79eb73408d9841abbde675',
    messagingSenderId: '885350117808',
    projectId: 'appod-3f4d9',
    authDomain: 'appod-3f4d9.firebaseapp.com',
    storageBucket: 'appod-3f4d9.appspot.com',
  );

}